//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceSync.PriceSrvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PriceSrvc.PriceSoap")]
    public interface PriceSoap {
        
        // CODEGEN: Generating message contract since element name Usr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePrices", ReplyAction="*")]
        PriceSync.PriceSrvc.DeletePricesResponse DeletePrices(PriceSync.PriceSrvc.DeletePricesRequest request);
        
        // CODEGEN: Generating message contract since element name Title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertTree", ReplyAction="*")]
        PriceSync.PriceSrvc.InsertTreeResponse InsertTree(PriceSync.PriceSrvc.InsertTreeRequest request);
        
        // CODEGEN: Generating message contract since element name Title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertValue", ReplyAction="*")]
        PriceSync.PriceSrvc.InsertValueResponse InsertValue(PriceSync.PriceSrvc.InsertValueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePricesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePrices", Namespace="http://tempuri.org/", Order=0)]
        public PriceSync.PriceSrvc.DeletePricesRequestBody Body;
        
        public DeletePricesRequest() {
        }
        
        public DeletePricesRequest(PriceSync.PriceSrvc.DeletePricesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePricesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        public DeletePricesRequestBody() {
        }
        
        public DeletePricesRequestBody(string Usr, string Pwd) {
            this.Usr = Usr;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePricesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePricesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PriceSync.PriceSrvc.DeletePricesResponseBody Body;
        
        public DeletePricesResponse() {
        }
        
        public DeletePricesResponse(PriceSync.PriceSrvc.DeletePricesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeletePricesResponseBody {
        
        public DeletePricesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertTreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertTree", Namespace="http://tempuri.org/", Order=0)]
        public PriceSync.PriceSrvc.InsertTreeRequestBody Body;
        
        public InsertTreeRequest() {
        }
        
        public InsertTreeRequest(PriceSync.PriceSrvc.InsertTreeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertTreeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Title;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short Priority;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Usr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Pwd;
        
        public InsertTreeRequestBody() {
        }
        
        public InsertTreeRequestBody(string Title, short Priority, string Usr, string Pwd) {
            this.Title = Title;
            this.Priority = Priority;
            this.Usr = Usr;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertTreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertTreeResponse", Namespace="http://tempuri.org/", Order=0)]
        public PriceSync.PriceSrvc.InsertTreeResponseBody Body;
        
        public InsertTreeResponse() {
        }
        
        public InsertTreeResponse(PriceSync.PriceSrvc.InsertTreeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertTreeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertTreeResult;
        
        public InsertTreeResponseBody() {
        }
        
        public InsertTreeResponseBody(int InsertTreeResult) {
            this.InsertTreeResult = InsertTreeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertValue", Namespace="http://tempuri.org/", Order=0)]
        public PriceSync.PriceSrvc.InsertValueRequestBody Body;
        
        public InsertValueRequest() {
        }
        
        public InsertValueRequest(PriceSync.PriceSrvc.InsertValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Diff;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Unit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int GroupId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Usr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Pwd;
        
        public InsertValueRequestBody() {
        }
        
        public InsertValueRequestBody(string Title, string Value, string Diff, string Unit, int GroupId, string Usr, string Pwd) {
            this.Title = Title;
            this.Value = Value;
            this.Diff = Diff;
            this.Unit = Unit;
            this.GroupId = GroupId;
            this.Usr = Usr;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public PriceSync.PriceSrvc.InsertValueResponseBody Body;
        
        public InsertValueResponse() {
        }
        
        public InsertValueResponse(PriceSync.PriceSrvc.InsertValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertValueResponseBody {
        
        public InsertValueResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PriceSoapChannel : PriceSync.PriceSrvc.PriceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceSoapClient : System.ServiceModel.ClientBase<PriceSync.PriceSrvc.PriceSoap>, PriceSync.PriceSrvc.PriceSoap {
        
        public PriceSoapClient() {
        }
        
        public PriceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceSync.PriceSrvc.DeletePricesResponse PriceSync.PriceSrvc.PriceSoap.DeletePrices(PriceSync.PriceSrvc.DeletePricesRequest request) {
            return base.Channel.DeletePrices(request);
        }
        
        public void DeletePrices(string Usr, string Pwd) {
            PriceSync.PriceSrvc.DeletePricesRequest inValue = new PriceSync.PriceSrvc.DeletePricesRequest();
            inValue.Body = new PriceSync.PriceSrvc.DeletePricesRequestBody();
            inValue.Body.Usr = Usr;
            inValue.Body.Pwd = Pwd;
            PriceSync.PriceSrvc.DeletePricesResponse retVal = ((PriceSync.PriceSrvc.PriceSoap)(this)).DeletePrices(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceSync.PriceSrvc.InsertTreeResponse PriceSync.PriceSrvc.PriceSoap.InsertTree(PriceSync.PriceSrvc.InsertTreeRequest request) {
            return base.Channel.InsertTree(request);
        }
        
        public int InsertTree(string Title, short Priority, string Usr, string Pwd) {
            PriceSync.PriceSrvc.InsertTreeRequest inValue = new PriceSync.PriceSrvc.InsertTreeRequest();
            inValue.Body = new PriceSync.PriceSrvc.InsertTreeRequestBody();
            inValue.Body.Title = Title;
            inValue.Body.Priority = Priority;
            inValue.Body.Usr = Usr;
            inValue.Body.Pwd = Pwd;
            PriceSync.PriceSrvc.InsertTreeResponse retVal = ((PriceSync.PriceSrvc.PriceSoap)(this)).InsertTree(inValue);
            return retVal.Body.InsertTreeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceSync.PriceSrvc.InsertValueResponse PriceSync.PriceSrvc.PriceSoap.InsertValue(PriceSync.PriceSrvc.InsertValueRequest request) {
            return base.Channel.InsertValue(request);
        }
        
        public void InsertValue(string Title, string Value, string Diff, string Unit, int GroupId, string Usr, string Pwd) {
            PriceSync.PriceSrvc.InsertValueRequest inValue = new PriceSync.PriceSrvc.InsertValueRequest();
            inValue.Body = new PriceSync.PriceSrvc.InsertValueRequestBody();
            inValue.Body.Title = Title;
            inValue.Body.Value = Value;
            inValue.Body.Diff = Diff;
            inValue.Body.Unit = Unit;
            inValue.Body.GroupId = GroupId;
            inValue.Body.Usr = Usr;
            inValue.Body.Pwd = Pwd;
            PriceSync.PriceSrvc.InsertValueResponse retVal = ((PriceSync.PriceSrvc.PriceSoap)(this)).InsertValue(inValue);
        }
    }
}
